defmodule RavixWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :ravix

  # The session is stored in the cookie and signed, so its contents can be
  # read but not tampered with. It carries the session token, so `Secure`
  # matters: without it the browser sends the token in the clear on a first
  # plaintext visit, before `force_ssl`'s redirect and before HSTS is cached.
  @session_options [
    store: :cookie,
    key: "_ravix_key",
    signing_salt: "FcRHQdEE",
    same_site: "Lax"
  ]

  @doc """
  The browser session cookie's name, so the preview gateway can scrub it in
  both directions rather than keeping its own copy of the name to drift from.
  """
  @spec session_cookie_name() :: String.t()
  def session_cookie_name, do: Keyword.fetch!(@session_options, :key)

  @doc """
  `@session_options` with `Secure` set when the app is actually reached over
  HTTPS. This follows `PUBLIC_URL` rather than the build: the browser suite
  runs the production build over plain HTTP on localhost, where a `Secure`
  cookie would be stored and never sent back.
  """
  @spec session_options() :: keyword()
  def session_options do
    case Ravix.Config.public_url() do
      "https://" <> _ -> Keyword.put(@session_options, :secure, true)
      _ -> @session_options
    end
  end

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Preview hosts (`*.PREVIEW_DOMAIN`) belong to the gateway, before static
  # files and before the session: an app running in a sprite must never see
  # the app's cookies, and the app must never answer for a preview host.
  plug RavixWeb.PreviewGateway

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :ravix,
    gzip: not code_reloading?,
    only: RavixWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :ravix
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug :session
  plug RavixWeb.Router

  # `session_options/0` reads runtime configuration, so the plug is built on
  # first use and kept rather than baked in at compile time.
  defp session(conn, _opts) do
    Plug.Session.call(conn, session_plug())
  end

  defp session_plug do
    case :persistent_term.get({__MODULE__, :session_plug}, nil) do
      nil ->
        opts = Plug.Session.init(session_options())
        :persistent_term.put({__MODULE__, :session_plug}, opts)
        opts

      opts ->
        opts
    end
  end
end
