import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { signIn, connectClaude } from './sign-in.js';

const mock = `http://localhost:${process.env.MOCK_PORT || 8893}`;

test('a flagged track copies secrets, becomes ready, and deletes its own machine and secrets on close', async ({ page, request }) => {
  test.setTimeout(180_000);
  await signIn(page, 'threadruntime', '/home');
  await connectClaude(page);
  await page.getByRole('button', { name: 'Add a project', exact: true }).first().click();
  const project = page.getByRole('dialog', { name: 'New project', exact: true });
  await project.getByLabel('Project name', { exact: true }).fill('Dedicated lifecycle');
  await project.getByRole('button', { name: 'Create project', exact: true }).click();
  await expect(project).toHaveCount(0);
  await page.locator('#yard .workspace-project.current .project-add').click();
  await page.getByRole('button', { name: 'Create track', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'New track', exact: true })).toHaveCount(0);
  await expect(page.locator('#track-machine-scope')).toHaveText('Own machine');
  await expect(page.locator('#track-setup-status')).toContainText('Prompts will wait until setup is ready.');
  await expect(page.locator('#track-setup-status')).toHaveCount(0, { timeout: 45_000 });
  const trackId = new URL(page.url()).pathname.split('/t/')[1];
  const response = await request.get(`${mock}/api/vaults`);
  const copies = (await response.json()).data.filter(v => v.metadata?.ravix?.track === trackId);
  expect(copies).toHaveLength(1);
  const vaultId = copies[0].id;
  const boxes = (await (await request.get(`${mock}/api/sandboxes`)).json()).data;
  const box = boxes.find(b => b.vault_id === vaultId);
  expect(box).toBeTruthy();
  const firstUrl = page.url();
  await page.locator('#yard .workspace-project.current .project-add').click();
  await page.getByRole('button', { name: 'Create track', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'New track', exact: true })).toHaveCount(0);
  // The New track dialog also changes the URL with ?new=track. Wait for a
  // distinct track path before recording the sibling's machine and vault.
  await expect(page).toHaveURL(url => url.pathname !== new URL(firstUrl).pathname && url.pathname.includes('/t/') && !url.search);
  await expect(page.locator('#track-machine-scope')).toHaveText('Own machine');
  await expect(page.locator('#track-setup-status')).toHaveCount(0, { timeout: 45_000 });
  const siblingId = new URL(page.url()).pathname.split('/t/')[1];
  const siblingCopies = (await (await request.get(`${mock}/api/vaults`)).json()).data;
  const siblingVault = siblingCopies.find(v => v.metadata?.ravix?.track === siblingId);
  expect(siblingVault).toBeTruthy();
  const siblingBoxes = (await (await request.get(`${mock}/api/sandboxes`)).json()).data;
  const siblingBox = siblingBoxes.find(b => b.vault_id === siblingVault.id);
  expect(siblingBox).toBeTruthy();
  expect(siblingBox.id).not.toBe(box.id);
  expect(siblingVault.id).not.toBe(vaultId);
  await page.goto(firstUrl);
  await expect(page.locator('[data-phx-main]')).toHaveClass(/phx-connected/);
  await expect(page.locator('#rebuild-track-machine')).toHaveCount(0);
  await page.getByRole('button', { name: 'Rebuild machine', exact: true }).click();
  const rebuild = page.getByRole('dialog', { name: 'Rebuild machine', exact: true });
  await expect(rebuild).toContainText("Rebuilding deletes only this track's machine");
  await expect(rebuild).toContainText('Sibling tracks are unaffected.');
  await rebuild.locator('input[type=checkbox]').check();
  await rebuild.getByRole('button', { name: 'Rebuild machine', exact: true }).click();
  await expect.poll(async () => (await (await request.get(`${mock}/api/sandboxes/${box.id}`)).json()).data.status, { timeout: 30_000 }).toBe("terminated");
  await expect(page.locator('#track-setup-status')).toHaveCount(0, { timeout: 45_000 });
  expect((await request.get(`${mock}/api/sandboxes/${siblingBox.id}`)).status()).toBe(200);
  expect((await request.get(`${mock}/api/vaults/${siblingVault.id}`)).status()).toBe(200);
  const rebuiltCopies = (await (await request.get(`${mock}/api/vaults`)).json()).data;
  const rebuiltVault = rebuiltCopies.find(v => v.metadata?.ravix?.track === trackId);
  expect(rebuiltVault.id).not.toBe(vaultId);
  const rebuiltBoxes = (await (await request.get(`${mock}/api/sandboxes`)).json()).data;
  const rebuiltBox = rebuiltBoxes.find(b => b.vault_id === rebuiltVault.id);
  expect(rebuiltBox.id).not.toBe(box.id);

  await page.locator('#yard .workspace-project.current button[title="Project settings"]').click();
  const settings = page.getByRole('dialog', { name: 'Project settings', exact: true });
  await settings.getByRole('button', { name: 'Agent', exact: true }).click();
  await expect(settings).toContainText('Changes the default agent for new threads. Existing threads keep their agent.');
  await expect(settings.locator('#project-rebuild-form')).toHaveCount(0);
  await settings.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'Close track', exact: true }).click();
  const close = page.getByRole('dialog', { name: 'Close track', exact: true });
  await expect(close).toContainText('uncommitted changes and unpushed commits will be deleted');
  await close.getByLabel('Delete machine, uncommitted changes and unpushed commits', { exact: true }).check();
  await close.getByRole('button', { name: 'Close track', exact: true }).click();
  await expect(page.locator('#track-setup-status')).toContainText('Closing… cleaning up this track\'s machine');
  await expect.poll(async () => (await (await request.get(`${mock}/api/sandboxes/${rebuiltBox.id}`)).json()).data.status, { timeout: 30_000 }).toBe("terminated");
  await expect.poll(async () => (await request.get(`${mock}/api/vaults/${rebuiltVault.id}`)).status()).toBe(404);
  const repeated = await request.delete(`${mock}/api/sandboxes/${rebuiltBox.id}`);
  expect(repeated.status()).toBe(422);
  expect((await repeated.json()).error).toBe('sandbox_not_resettable');
  expect((await (await request.get(`${mock}/api/sandboxes/${rebuiltBox.id}`)).json()).data.status).toBe('terminated');
});


test('an owner confirms an uncertain secret change and can save again', async ({ page }) => {
  await signIn(page, 'threadruntime', '/home');
  await connectClaude(page);
  await page.getByRole('button', { name: 'Add a project', exact: true }).first().click();
  const project = page.getByRole('dialog', { name: 'New project', exact: true });
  await project.getByLabel('Project name', { exact: true }).fill('Secret change recovery');
  await project.getByRole('button', { name: 'Create project', exact: true }).click();
  await expect(project).toHaveCount(0);
  const projectId = new URL(page.url()).pathname.split('/p/')[1];
  const { database } = JSON.parse(readFileSync(`tmp/browser-${process.env.BROWSER_PORT || 4103}.json`, 'utf8'));
  if (!/^ravix_browser_[a-f0-9]{32}$/.test(database) || !/^[a-f0-9-]{36}$/.test(projectId)) throw new Error('Invalid browser fixture');
  const server = process.env.BROWSER_DATABASE_SERVER || 'postgres://postgres:postgres@localhost:5432';
  const sql = query => execFileSync('psql', [`${server}/${database}`, '-XAtq', '-v', 'ON_ERROR_STOP=1', '-c', query], { encoding: 'utf8' }).trim();
  // Persisted state after a provider timeout or worker loss. Only this harness's database.
  sql(`UPDATE ravix.projects SET secrets_pending = true, secrets_generation = 1 WHERE id = '${projectId}'`);
  await page.locator('#yard .workspace-project.current button[title="Project settings"]').click();
  const settings = page.getByRole('dialog', { name: 'Project settings', exact: true });
  await settings.getByRole('button', { name: 'Secrets', exact: true }).click();
  const confirmation = page.locator('#secret-confirmation-form');
  await expect(confirmation).toContainText('Values cannot be checked here');
  await confirmation.getByLabel('I confirmed the previous secret change has finished in Fountain.', { exact: true }).check();
  await confirmation.getByRole('button', { name: 'Confirm and unlock secret changes', exact: true }).click();
  await expect(confirmation).toHaveCount(0);
  expect(sql(`SELECT secrets_pending FROM ravix.projects WHERE id = '${projectId}'`)).toBe('f');
  await settings.getByLabel('Store', { exact: true }).selectOption('vault');
  await settings.getByLabel('Key', { exact: true }).fill('RECOVERY_TEST');
  await settings.getByLabel('Value', { exact: true }).fill('browser-fixture-only');
  await settings.getByRole('button', { name: 'Update secret', exact: true }).click();
  await expect(settings).toContainText('RECOVERY_TEST');
  expect(sql(`SELECT secrets_generation || ':' || secrets_pending FROM ravix.projects WHERE id = '${projectId}'`)).toBe('2:false');
});
