import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { signIn, connectClaude } from './sign-in.js';

test('diff review persists across reload, replies and resolves from Changes and Checks', async ({ page }) => {
  test.setTimeout(180_000);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await signIn(page, 'inspectordiff');
  await connectClaude(page);
  await page.getByRole('button', { name: 'Add a repository', exact: true }).first().click();
  const project = page.getByRole('dialog', { name: 'Add a repository', exact: true });
  await project.getByLabel('Project name', { exact: true }).fill('Review Atlas');
  await expect(project.locator('#project-repositories input[type=radio]')).not.toHaveCount(0);
  await project.getByRole('radio', { name: 'mockuser/atlas-api', exact: true }).check();
  await project.getByRole('button', { name: 'Add repository', exact: true }).click();
  await expect(project).toBeHidden();
  await page.locator('#yard .workspace-project.current .project-add').click();
  const dialog = page.getByRole('dialog', { name: 'New track', exact: true });
  await dialog.getByRole('button', { name: 'Create track', exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(page.getByRole('textbox', { name: 'Message', exact: true })).toBeEnabled({ timeout: 30_000 });
  const panels = page.getByRole('navigation', { name: 'Inspector panels' });
  await panels.getByRole('button', { name: 'Changes', exact: true }).click();
  await page.locator('.change-file', { hasText: 'window.ts' }).click();
  const anchor = page.locator('button[phx-click=review-anchor][phx-value-side=new]').first();
  await anchor.click();
  await page.locator('#review-body').fill('Please verify the offset when clocks change.');
  await page.locator('#review-post-form button[type=submit]').click();
  const discussion = page.locator('.review-discussion');
  await expect(discussion).toHaveCount(1);
  await expect(discussion).toContainText('Please verify the offset when clocks change.');
  const discussionId = await discussion.getAttribute('id');
  await discussion.locator('textarea').fill('Verified both offset transitions.');
  await discussion.locator('button[type=submit]').click();
  await expect(discussion).toContainText('Verified both offset transitions.');
  await discussion.locator('button[phx-click=review-resolve]').click();
  await expect(discussion.locator('button[phx-click=review-resolve]')).toHaveAttribute('phx-value-resolved', 'false');
  const url = page.url();
  await page.reload();
  await expect(page.locator('[data-phx-main]')).toHaveClass(/phx-connected/);
  await panels.getByRole('button', { name: 'Checks', exact: true }).click();
  await expect(page.locator(`#${discussionId}`)).toContainText('Verified both offset transitions.');
  await page.locator('a[phx-click=review-jump]').click();
  await expect(page.locator(`#${discussionId}`)).toHaveAttribute('data-selected', 'true');
  await expect(page.locator('button[phx-click=review-anchor][phx-value-side=new]').first()).toBeAttached();
  await page.locator(`#${discussionId}`).scrollIntoViewIfNeeded();
  if (process.env.SCREENSHOT_DIR) await page.screenshot({ path: `${process.env.SCREENSHOT_DIR}/diff-review-desktop.png` });
  const axe = await new AxeBuilder({ page }).include('#diff-review')
    .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze();
  expect(axe.violations).toEqual([]);
  await page.setViewportSize({ width: 390, height: 844 });
  // Reopening the inspector uses the same navigation on a narrow screen.
  await page.goto(url);
  await expect(page.locator('[data-phx-main]')).toHaveClass(/phx-connected/);
  await panels.getByRole('button', { name: 'Changes', exact: true }).click();
  await page.locator('a[phx-click=review-jump]').click();
  await page.locator(`#${discussionId}`).scrollIntoViewIfNeeded();
  await expect(page.locator(`#${discussionId}`)).toBeVisible();
  if (process.env.SCREENSHOT_DIR) await page.screenshot({ path: `${process.env.SCREENSHOT_DIR}/diff-review-mobile.png` });
});
