apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: switchyard-tls
  namespace: switchyard
spec:
  secretName: switchyard-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - switchyard.demo.managoat.com
