apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ravix-tls
  namespace: ravix
spec:
  secretName: ravix-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - app.ravix.sh
