apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ravix
  namespace: ravix
  labels:
    app: ravix
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`app.ravix.sh`)"
      kind: Rule
      services:
        - name: ravix
          port: 80
  tls:
    secretName: ravix-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ravix-http
  namespace: ravix
  labels:
    app: ravix
spec:
  entryPoints:
    - web
  routes:
    - match: "Host(`app.ravix.sh`)"
      kind: Rule
      middlewares:
        - name: redirect-https
          namespace: default
      services:
        - name: ravix
          port: 80
