apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ravix-data
  namespace: ravix
  labels:
    app: ravix
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
