apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: switchyard-data
  namespace: switchyard
  labels:
    app: switchyard
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
